version: '3.7'
services:
  backend:
    container_name: backend
    command:
      - mvn clean package
      - java -jar target/green-food-api-*-SNAPSHOT.jar
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
#    environment:
#      REACT_APP_BACKEND_API_BASE_URL: "http://localhost:7777"
    depends_on:
      - backend
